### ISSUE TITLE
Segmentation fault in GW real-axis

### ISSUE THREAD

**Issue by attacc** [yambo-code/yambo#162]
Dear all

with intel fortran compiler I get a segmentation fault in ioX.F in the real-axis GW, 
in the LiF test, line

     if (allocated(X_par)) then
       call def_variable_bulk(ID_frag,trim(ch),1,(/2,X%ng_db,X%ng_db,Xw%n_freqs/),SP)
       call  io_variable_bulk(ID_frag,1,C3=X_par(1)%blc(:,:,:Xw%n_freqs),IPOS=(/1,X_par(1)%rows(1),X_par(1)%cols(1),1/))
     endif

here the tests
https://media.yambo-code.eu/robots/GPL/5.3/attacc-lavoro_5.3_1_error.php

it is not clear to me how to solve it, I just report it here

best
Claudio

**Comment by attacc** [comment]
It crashed before writing anything of these lines
It seems there is a problem acceding to X_par(1)%blc.
Even with debug flags situation does not change
Probably some operations corrupt memory where is allocated X_par(1)%blc

Program received signal SIGSEGV, Segmentation fault.
0x00000000005f5aab in io_x (x=..., xw=..., id=1) at io_X.f90:295
295	     write(*,*) allocated(X_par(1)%blc)
(gdb) where
#0  0x00000000005f5aab in io_x (x=..., xw=..., id=1) at io_X.f90:295
#1  0x00000000004bef82 in io_x_.t28023p.t28043p.t28067p () at QP_real_axis.f90:411
#2  qp_real_axis (x=..., xen=..., xk=..., en=..., k=..., q=..., qp=..., xw=..., dip=..., gw_iter=-498644) at QP_real_axis.f90:417
#3  0x00000000004a031b in qp_real_axis_.t12182p.t12202p.t12388p.t12700p.t12886p.t13198p.t13510p.t13630p.t13654p.t13671p ()
    at QP_newton.f90:70
#4  qp_newton (x=..., xen=..., xk=..., en=..., k=..., q=..., qp=..., xw=..., dip=...) at QP_newton.f90:76
#5  0x000000000049c849 in qp_newton_.t15762p.t15782p.t15968p.t16280p.t16466p.t16778p.t17090p.t17210p.t17234p () at QP_driver.f90:326
#6  qp_driver (x=..., xen=..., xk=..., en=..., k=..., q=..., xw=..., dip=...) at QP_driver.f90:330
#7  0x0000000000419f8a in yambo (np=<optimized out>, pid=<optimized out>, lnstr=<optimized out>, iinf=<optimized out>, 
    iind=<optimized out>, iod=<optimized out>, icd=<optimized out>, ijs=<optimized out>, instr=..., inf=..., ind=..., od=..., 
    com_dir=..., js=..., _instr=<optimized out>, _inf=<optimized out>, _ind=<optimized out>, _od=<optimized out>, 
    _com_dir=<optimized out>, _js=<optimized out>) at yambo.f90:213
#8  0x000000000078efd6 in launcher ()
#9  0x000000000078e292 in main ()
(gdb)

**Comment by attacc** [comment]
Fixed... then I will send new tests

**Comment by attacc** [comment]
Fixed in Version 5.3.0,  Revision 23888,  Hash 8803efb31
